# Generated by Django 4.2 on 2023-05-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_bicycle_alter_post_date_pub"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bicycle",
        ),
    ]
